### PR TITLE
Allow cancellable promises that abort the request

### PR DESCRIPTION
**Pull request by markdalgleish**
Let me know if you'd like us to make any changes :)

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Thanks for the fantastic pull request! I didn't even know you could cancel promises :) Yeah for open source—it's really nice having smart open source colleagues all around the world :)

**Comment by KyleAMathews** [comment]
Released a 1.1.0.

**Comment by KyleAMathews** [comment]
Also interested in being added as maintainer for this project? I'm a big fan of "open open source" and you clearly know more about promises than me :)

**Comment by markdalgleish** [comment]
I'd love to be a maintainer! Thanks for offering :)

**Comment by KyleAMathews** [comment]
Added! Thanks for your help so far! My only rule is we do all work in PRs and for major changes, get a signoff from at least one other maintainer before merging.

**Comment by markdalgleish** [comment]
Great, I wouldn't have it any other way :)

**Pull request merged**
