### PR TITLE
Modified a error message

### PR DESCRIPTION
**Pull request by kumatch**
Modified a error message creation. (Because I catch the error running on browser with webpack.)

### CODE REVIEW

**Comment by KyleAMathews** [comment]
@kumatch thanks for the PR!

What were the errors you were seeing with Webpack?

Could you update your PR please to resolve the conflicts?

**Comment by kumatch** [comment]
@KyleAMathews 

https://github.com/KyleAMathews/superagent-bluebird-promise/blob/be47e5ced2a6453953a42af53e0a3eb5aa5dcf95/index.js#L39

First I caught the error "Uncaught TypeError: Cannot read property 'method' of undefined". The `self` don't have `req` member.

In Browser build (ex. Webpack, browserify) SuperAgent instance is `lib/client.js`, not `lib/node/agent.js`. It's writing "browser" field in package.json (I understand in this case also).

Then I re-modified error message using Response's toError. It's simply but this change remove host information from message so please fix it if you are not like.

**Comment by KyleAMathews** [comment]
@kumatch I opened a new PR with your code with some slight modifications — can you review? https://github.com/KyleAMathews/superagent-bluebird-promise/commit/bef2de0ba73edbc5d69505bcc5c2abfe81d139c7

The main change was I do like having the full URL in the error message.

**Comment by kumatch** [comment]
@KyleAMathews 
Thanks!
It's fine and works on Node/browser with the error message includes full URL.

**Pull request merged**
