### PR TITLE
Fixed issue with enabling cancellation after promises are created

### PR DESCRIPTION
**Pull request by patrickhulce**

### CODE REVIEW

**Comment by patrickhulce** [comment]
Addresses #50

**Comment by LudwikJaniuk** [comment]
+1
This bug made me leave superagent-bluebird-promise for superagent-promise

**Comment by markdalgleish** [comment]
Thank you! Sorry for the delay on merging this, but really appreciate your work here.

**Comment by richardschneider** [comment]
Do you plan on releasing to NPM?

**Comment by KyleAMathews** [comment]
@richardschneider is it not in the 4.10 release? https://www.npmjs.com/package/superagent-bluebird-promise

**Pull request merged**
