### PR TITLE
Fixed bluebird 3.0.0 compatability

### PR DESCRIPTION
**Pull request by janpieterz**
I've added the fixes needed. 

I could not get the tests to even compile or run on my Windows machine. I saw a lot that are going to be a lot different, but I can't run them, so I'm unsure how to progress from here. Perhaps someone else can take a hit at that?

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Huh... no idea why tests won't run on Windows. TravisCI just ran and *most* passed.

**Comment by janpieterz** [comment]
Both of those also are not applicable anymore, bluebird doesn't throw an error so that seems to suggest that means just removing them and that should be it.

**Comment by nickclaw** [comment]
I don't think you can remove those tests, according to the bluebird docs (http://bluebirdjs.com/docs/api/cancellationerror.html), CancelationError is still used.

**Comment by nickclaw** [comment]
Although I can't seem to get it appear either..

**Comment by janpieterz** [comment]
Yeah, I encountered the same. Could not trigger them using a normal cancel, the docs also don's specify this anymore except on the specific error. Perhaps we can ask the maintainer for some clarification?

**Comment by KyleAMathews** [comment]
This looks good to me. @janpieterz can you fix the merge conflicts? @markdalgleish, @spudly, @kumatch, @jordansexton, @madarche, others any comment?

**Comment by madarche** [comment]
Hello @KyleAMathews,

First thanks to everyone working on the issue!

I have  `npm install bluebird@3.0.5` and `npm install https://github.com/janpieterz/superagent-bluebird-promise.git` on 4 fairly complex projects and the issue is unmistakably fixed by this PR (all unit tests are passing). Great!

But shouldn't this PR also update the `package.json` file with a `peerDependency` to `bluebird": "3.x"` ?

Cheers

**Comment by KyleAMathews** [comment]
@madarche yup, good catch.

**Comment by madarche** [comment]
And here is some other data: `npm test` works with 0 failures for me on `https://github.com/janpieterz/superagent-bluebird-promise.git`. But if I add back the 2 removed tests, they fail. I'm not saying that the 2 removed should be added back, I'm just giving the information that they fail if they're here. I've had no time to read look into them.

**Comment by janpieterz** [comment]
Solved (sorry for the wait, had a busy week). Also updated the peerDependency to 3.x.

I removed those tests in the assumption that the CancellationError is different than it's usage before (2.x). I couldn't find anything in the docs besides the API reference, nor any way to trigger the CancellationError to occur. Any help/ideas are more than welcome.

**Comment by spalger** [comment]
+1

**Comment by Reggino** [comment]
+1 nice

**Comment by Dignifiedquire** [comment]
@KyleAMathews any updates on merging and releasing this?

**Comment by KyleAMathews** [comment]
3.0.0 released! Thanks for your patience everyone.

**Comment by KyleAMathews** [comment]
@janpieterz and anyone else around, is the README documentation still correct for canceling requests https://github.com/KyleAMathews/superagent-bluebird-promise/#cancelling-requests ?

**Comment by janpieterz** [comment]
@KyleAMathews I've got a cancelled request here that seems to work with the same API, although the text around it is actually incorrect, sorry for not spotting that.

**Comment by janpieterz** [comment]
It kind of seems you could simply omit everything after the line `promise.cancel();`, although you could also choose to omit this since yo're basically repeating the documentation of bluebird since it's a returned promise.

**Comment by KyleAMathews** [comment]
So... keep it?

**Comment by janpieterz** [comment]
I've added in my fork the content that is still applicable (according to me).
https://github.com/janpieterz/superagent-bluebird-promise/blob/master/README.md

**Comment by KyleAMathews** [comment]
@janpieterz thanks! I cherry-picked your commit.

**Comment by markdalgleish** [comment]
Wow, I love how much simpler cancellation is in Bluebird v3. Thanks @janpieterz for this PR, it's greatly appreciated :)

**Pull request merged**
