### PR TITLE
Support for superagent 2.0.0 and higher

### PR DESCRIPTION
**Pull request by dolezel**

### CODE REVIEW

**Comment by francof** [comment]
Is this being merged, or is the project abanoned?

**Comment by KyleAMathews** [comment]
I'm not familiar with the Superagent 2.0.0 release. Is there any breaking changes that affect this library?

**Comment by dolezel** [comment]
Hi, I'm using it with no problem, there should be no changes affecting this library ( https://github.com/visionmedia/superagent/blob/master/History.md )

**Comment by KyleAMathews** [comment]
Sounds good then!

**Comment by KyleAMathews** [comment]
3.0.2 published.

**Pull request merged**
